### ISSUE TITLE
Table Of Contents in 100.7 does not show Feature Collection Layer

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-toolkit-dotnet#304] opened 2020-02-07 22:56 UTC
I upgraded toolkit from 100.4 to 100.7 then noticed Table Of Contents is empty. So I created a test project and discovered that 100.7 does not show Feature Collection Layer. Attached are the screenshots for comparison and a sample code. Please advise if this is by design or a bug. Thanks!

Toolkit 100.4
![MapView_100_4](https://user-images.githubusercontent.com/8011074/74071877-0fc95000-49d3-11ea-8a38-a16ad102f8bd.PNG)

Toolkit 100.7
![MapView_100_7](https://user-images.githubusercontent.com/8011074/74071878-1061e680-49d3-11ea-851b-b796716d33a9.PNG)

Sample Code:
[WpfApp1.zip](https://github.com/Esri/arcgis-toolkit-dotnet/files/4173228/WpfApp1.zip)

**Comment by dotMorten** [comment] 2020-02-09 04:25
Thanks for the good reproducer. Makes my life sooo much easier :-)
I can reproduce.
The problem isn't with feature collection, but with layers getting added after it's been assigned. So a workaround for now is to add the collection first before assigning it to the mapview / ToC.

**Comment by dotMorten** [comment] 2020-02-09 07:31
This is now fixed with the latest code in master. Thank you again!

**Closed** 2020-02-09 07:31 UTC
