### ISSUE TITLE
Invisible features when add Legend or LayerLegend functionality in Xamarin Forms for Android

### ISSUE THREAD

**Issue by gkmiel** [Esri/arcgis-toolkit-dotnet#241] opened 2018-11-06 08:51 UTC
I use MVVM in my application and have tested with toolkit 100.4. 
If I set ItemsSource for LayerLegend, layers disappear from the map but exist in layer legend. I have found that it does not work when layers are from ArcGIS server FeatureService or MapService. More info you can find here: 
https://community.esri.com/message/795260-re-invisible-features-when-add-legend-or-layerlegend-functionality-from-runtime-toolkit?commentID=795260&et=watches.email.thread#comment-795260

The same problem was with Legend control in previous toolkit versions. I haven't tested it with 100.4

**Comment by dotMorten** [comment] 2018-11-06 18:53
@gkmiel I don't have much to go on from the description, but could this be because the layers are going in and out of scale range?
The control can be set to filter based on scale range as well using the `FilterByVisibleScaleRange` property:
https://github.com/Esri/arcgis-toolkit-dotnet/blob/master/src/Esri.ArcGISRuntime.Toolkit/Common/UI/Controls/LayerList/LayerList.cs#L86

For this to work, it's not just enough to set the itemssource, but also the GeoView property so it can track the current scale.

**Comment by gkmiel** [comment] 2018-11-07 12:53
Hi Morten,
My application is multiplatform. Application works well on UWP. I don’t have possibility to check it on IOs.
It works fine with Android when I use ArcGIS Runtime sample data from ArcGIS Online or my geodatabase package.
It not works with Android only with ArcServer services.

This is my xaml  file content

                <controls:ItemsControl x:Name="MyLegend" ItemsSource="{Binding NetworkLayers, Source={StaticResource MapViewModel}}" Margin="10">
                    <controls:ItemsControl.ItemTemplate>
                        <DataTemplate>
                            <StackLayout>
                                <StackLayout Orientation="Horizontal">
                                    <Label Text="{Binding Name}" FontAttributes="Bold" />
                                    <Switch IsToggled="{Binding IsVisible, Mode=TwoWay}"/>
                                </StackLayout>
                                <esriTK:LayerLegend LayerContent="{Binding}" IncludeSublayers="True" Margin="10,0"/>
                            </StackLayout>
                        </DataTemplate>
                    </controls:ItemsControl.ItemTemplate>
                </controls:ItemsControl>


            <esriUI:MapView Grid.Column="1" x:Name="MyMapView" Map="{Binding Map, Source={StaticResource MapViewModel}}" local:CommandBinder.RequestView="{Binding ViewpointRequested}" >
                <esriUI:MapView.Behaviors>
                    <local:EventToCommandBehavior EventName="GeoViewTapped" Command="{Binding GeoViewTappedCommand}" Converter="{StaticResource GeoViewTappedConverter}" />
                    <local:EventToCommandBehavior EventName="NavigationCompleted" Command="{Binding ViewpointChangedCommand}" Converter="{StaticResource ViewpointChangedConverter}"/>
                </esriUI:MapView.Behaviors>


If I set NetworkLayers property in MapViewModel, my features disappear

        public LayerCollection NetworkLayers
        {
            get
            {
//                if (Device.RuntimePlatform == Device.Android) return null;
                return Map.OperationalLayers;
            }
        }

Best regards,
Gintautas

**Comment by dotMorten** [comment] 2020-01-22 23:35
I have not been able to reproduce this with the provided info. However I just merged a complete rewrite of the Legend control that overall works a lot better. I'd suggest you try that out, and if still an issue, feel free to reopen and if possible provide a small sample that reproduces the issue.

**Closed by dotMorten** 2020-01-22 23:35 UTC
Labels: Priority: Medium, Type: Bug
