### ISSUE TITLE
Table of Contents Issues in v100.7

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-toolkit-dotnet#308] opened 2020-02-14 15:38 UTC
Thank you for fixing the bug to show feature collection layer. I built the newest code and tested it, but there are some new issues.

v 100.7
![Capture](https://user-images.githubusercontent.com/8011074/74543040-b2715980-4f12-11ea-8384-0693ae90bc10.PNG)

1. TOC does not show basemap "World Imagery". v100.4 does not have this issue.

2. The order of sub layers under Feature Collection in TOC is not the same as the display order on the map. On the map, triangle is on the top, line is in the middle, circle is at the bottom, but this order is reversed in TOC. I guess TOC is reading the order from the sub layer list of Feature Collection. However, that list stores layers bottom-most first. So, I believe TOC should reverse that order before showing it. v100.4 has the same issue.

3. TOC does not refresh when I add, remove, move up, and move down sub layers. I added some customized buttons into TOC's context menu. The map is working correctly when I click the buttons, but TOC does not refresh. v100.4 does not have this issue.

Below is the source code for your testing.
[WpfApp1.zip](https://github.com/Esri/arcgis-toolkit-dotnet/files/4205062/WpfApp1.zip)

Thanks!

**Comment by dotMorten** [comment] 2020-02-14 20:11
Again thank you for the great reproducer and detailed explanation.
The reason you're not seeing the basemap is that you didn't give it a name to display.
Easy fix though:
`mapView.Map.Basemap.Name = "My basemap";`
![image](https://user-images.githubusercontent.com/1378165/74563993-d6d53200-4f22-11ea-94d3-399df46f3c88.png)

One change in behavior is that basemap is now shown as a single entity, instead of showing reference layers on top of the operational layers, and base layers below.

In the future we might add two sections below the basemap section showing the base and reference layers.

I'm still working on the other issues...

**Comment by GeoITwinkle** [comment] 2020-02-14 20:18
Oh, I see. I've never noticed that I need to assign a name for basemap, since TOC shows it by default in v100.4. I will change my code in v100.7.

Thanks for working on other issues. The context menu is very handy so that I can add many customized functions. If the order and refresh is working correctly, it will be perfect.

**Comment by dotMorten** [comment] 2020-02-14 21:58
@GeoITwinkle I have a branch with fixes. Going through testing I didn't break anything, but so far looking good (had to move some code around so Legend and ToC share more code and can share the same fixes and not duplicate code for tracking changes to the layer tree.)

**Comment by dotMorten** [comment] 2020-02-14 22:07
Should be fixed with the latest changes. Again thank you for the detailed info and reproducer.
Let me know if you're still seeing issues.

**Closed by dotMorten** 2020-02-14 22:07 UTC

**Comment by dotMorten** [comment] 2020-02-14 22:10
Btw, make sure you also name your feature collection layer, and feature collection tables:

```cs
  this.collectionLayer = new FeatureCollectionLayer(featuresCollection);
  collectionLayer.Name = "Feature Collection";
  ...
  FeatureCollectionTable polysTable = ...;
  polysTable.DisplayName = "Polygons";
```
![image](https://user-images.githubusercontent.com/1378165/74572252-aa75e180-4f33-11ea-928b-b152a694bf37.png)

**Comment by GeoITwinkle** [comment] 2020-02-15 02:30
Thank you very much for the reminder and quick fix. I built the latest code and it shows correct order and refreshes when moving up/down layers. Thanks again and have a good weekend!

**Comment by dotMorten** [comment] 2020-02-15 03:27
Good simple reproducers usually result in quicker fixes 😉
