### ISSUE TITLE
On Xamarin.Forms project, legend appears correctly for UWP, but not for Android or iOS when using local geodatabase

### ISSUE THREAD

**Issue by cmpalmer66** [Esri/arcgis-toolkit-dotnet#250] opened 2019-04-10 22:12 UTC
Our application uses a shared project and Xamarin.Forms. We're operating in offline mode with a synced local (SQLite) geodatabase. On UWP, we have no issues with the Legend appearing with the correct information. However, with the same XAML and ViewModel, the Legend never appears on Android or iOS. We've tried displaying it in several different ways and places, but it never seems to populate or show.

```
<ScrollView Grid.Column="0">
     <esriTK:Legend HorizontalOptions="Start" VerticalOptions="Start" 
            IsVisible="True" GeoView="{x:Reference MV}" />
</ScrollView>
```

**Comment by dotMorten** [comment] 2019-05-14 23:25
Potentially duplicate of #241

**Comment by osamaelhosany** [comment] 2019-09-22 13:15
I Added legend control From C# not Xaml and worked fine with me 
`private void CreateLegend() {
            Legend templegend = new Legend();
            templegend.BindingContext = this.esriMap; // esrimap is my mapView
            templegend.SetBinding(Legend.GeoViewProperty, ".", BindingMode.TwoWay);
            templegend.HorizontalOptions = LayoutOptions.FillAndExpand;
            templegend.VerticalOptions = LayoutOptions.FillAndExpand;
            templegend.ReverseLayerOrder = true;
            templegend.FilterByVisibleScaleRange = true;
            templegend.BackgroundColor = Color.Transparent;
            legendgrid.Children.Add(templegend); // legendgird is my parent grid }`

**Comment by dotMorten** [comment] 2020-01-22 23:34
I have not been able to reproduce this with the provided info. However I just merged a complete rewrite of the Legend control that overall works a lot better. I'd suggest you try that out, and if still an issue, feel free to reopen and if possible provide a small sample that reproduces the issue.

**Closed by dotMorten** 2020-01-22 23:34 UTC
Labels: Type: Bug
