### ISSUE TITLE
OverviewMap

### ISSUE THREAD

**Issue by mbranscomb** [Esri/arcgis-toolkit-dotnet#206] opened 2018-04-18 20:13 UTC
OverviewMap shows a smaller scale overview of the visible area for the associated MapView.

- [ ] UWP 
- [ ] WPF 
- [ ] Xamarin.Android 
- [ ] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by ldanzinger** [comment] 2018-11-29 15:30
@mbranscomb there are additional requests to have it work bidirectionally, so that you can drag the extent in the overview map and have that update the main map - https://community.esri.com/thread/221870-move-overview-map

**Comment by nCastle1** [comment] 2021-06-14 19:21
Duplicate of #360

**Closed** 2021-06-14 19:21 UTC
Labels: Closed: Duplicate, Type: Feature
