### ISSUE TITLE
TOC does not work with group layers on version 100.1

### ISSUE THREAD

**Issue by kerenco75** [Esri/arcgis-toolkit-dotnet#132] opened 2017-08-02 06:25 UTC
TOC does not work with group layers on version 100.1
It only opens the parents level and not as a treeview for drill down

**Comment by dotMorten** [comment] 2017-08-18 18:39
Use this webmap:
http://ess.maps.arcgis.com/home/webmap/viewer.html?webmap=f1ed0d220d6447a586203675ed5ac213

Expected (worked in v100):
![image](https://user-images.githubusercontent.com/1378165/29472677-bda091b2-8409-11e7-91af-8ce6cb6039fe.png)

Current (not working in v100.1):
![image](https://user-images.githubusercontent.com/1378165/29472690-ca462eb8-8409-11e7-992d-ebff18a21f87.png)

**Comment by kerenco75** [comment] 2017-08-20 04:20
I would like to understand better
Is this a problem that has to be fixed within the core or within the arcgis-toolkit-dotnet solution?

**Comment by dotMorten** [comment] 2017-08-21 19:01
In my first round of looking at this, it seems that the problem is with this `return` statement.  If you remove it, the sub layers will populate:
https://github.com/Esri/arcgis-toolkit-dotnet/blob/687545da529fdf4bfb18aac4e1e683d58b92b206/src/Esri.ArcGISRuntime.Toolkit/WPF/UI/Controls/TableOfContents/LayerContentViewModel.cs#L115

**Comment by dotMorten** [comment] 2017-08-21 19:34
Pushed a fix in to resolve this.

**Comment by kerenco75** [comment] 2017-08-26 19:43
After I did the change I sometimes encounter with the following error:

System.InvalidOperationException: Collection was modified;
enumeration operation may not execute.

at
System.ThrowHelper.ThrowInvalidOperationException(ExceptionResour
ce resource)

at System.Collections.Generic.List‘1.Enumerator.MoveNextRareO

at
System.Linq.Enumerable.WhereSelectEnumerableIterator‘2.MoveNextO

at System.Collections.Generic.List‘1..ctor(IEnumerable‘1 collection)

at
med s.Map.UI.TableOfContent.LayerContentViewM od el. < BuildSublayerL
ist> d_16.MoveNextO in
c:\Users\tamarre\Source\Workspaces\SitaWare\Main\Source\meds.Ma
p\U1\TableOfContent\LayerContentViewModel.cs:line 116
End of stack trace from previous location where exception was
thrown

at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.< > c.<Thro
wAsync> b_6_0(Obj ect state)

at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegat
e callback, Object args, Int32 numArgs)

at
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object
source, Delegate callback, Object args, Int32 numArgs, Delegate
catchHandler)

at System.Windows.Threading.DispatcherOperation.InvokeImplO

at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)

at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)

at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)

at System.Windows.Threading.DispatcherOperation.InvokeO

at System.Windows.Threading.Dispatcher.ProcessQueueO

at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd,
Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr
wParam, IntPtr lParam, Boolean& handled)

at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object 0)

at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegat
e callback, Object args, Int32 numArgs)

at
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object
source, Delegate callback, Object args, Int32 numArgs, Delegate
catchHandler)

at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPri
ority priority, TimeSpan timeout, Delegate method, Object args, Int32
numArgs)

at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg,
IntPtr wParam, IntPtr lParam)

at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

at
System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFram
e frame)

at System.Windows.Application.RunDispatcher(Object ignore)

at System.Windows.Application.RunInternal(Window window)

at meds.Desktop.App.MainO in
c:\Users\tamarre\Source\Workspaces\SitaWare\Main\Source\meds.Des
ktop\obj\Debug\App.g.cs:Iine 0

**Comment by dotMorten** [comment] 2017-08-28 17:14
@kerenco75 Could you try pulling the entire latest v100 branch? There was another commit shortly after that also cleaned up the indices in the collection.

If that doesn't help, could you share a sample and steps that reproduces this error?

**Closed** 2017-10-20 23:45 UTC
Labels: A-bug, B-high, C-S, D-to verify
